### ISSUE TITLE
Possible Typo in Assignment 3

### ISSUE THREAD

**Issue by jpapon** [cs231n/cs231n.github.io#11]
In q1 Dropout section it sets the dropout parameters to the following to numerically check the *backward* pass of dropout:

```
dropout_param = {'p': 0.8, 'mode': 'test', 'seed': 123}
```

This doesn't make much sense - shouldn't mode be set to 'train'?

**Comment by jcjohnson** [comment]
Good catch - you're right.

Technically you *can* compute a backward pass for dropout in testing mode, but it is trivial and will never happen during training. It's much more important to test the backward pass for training mode.

I'll fix it an upload a new version of the assignment.

**Comment by karpathy** [comment]
Thanks @jpapon !
