### ISSUE TITLE
Cannot find AMI for cs231n_caffe_torch7_keras_lasagne_v2 on AWS

### ISSUE THREAD

**Issue by yeshg** [cs231n/cs231n.github.io#119]
From [this](http://cs231n.github.io/aws-tutorial/) tutorial,

After searching for cs231n_caffe_torch7_keras_lasagne_v2 in the Community AMIs search bar there are no results. The page says there are No AMIs found matching your filter criteria:

I tried searching for ami-125b2c72 as well, but AWS still said that no AMIs matched the criteria. I haven't selected any filters on the side bar, and am searching in the Community AMIs tab, not the AWS Marketplace.

Is anyone else having this issue?

**Comment by jcjohnson** [comment]
Make sure you are searching in the US West (Northern California) region.

**Comment by yeshg** [comment]
Thanks! That was the issue.
