### ISSUE TITLE
coco_captioning.zip and pretrained_model.h5 are gone

### ISSUE THREAD

**Issue by philippIO** [cs231n/cs231n.github.io#131]
Have you taken the files off or did the path change to _http://cs231n.stanford.edu/coco_captioning.zip_ ?
Would be great if you could put them back up.

**Comment by jcjohnson** [comment]
Sorry about that - I was reorganizing the website a bit yesterday. Both files should be back now.

**Comment by philippIO** [comment]
Thanks!
Great work by the way. I really enjoyed the exercises thus far.
