### ISSUE TITLE
where to get the class video ?

### ISSUE THREAD

**Issue by loveJasmine** [cs231n/cs231n.github.io#159]

**Comment by moizsajid** [comment]
Justin mentioned on Reddit that the video lectures will be released by the end of June. https://www.reddit.com/r/cs231n/comments/67izzs/youtube_videos_of_lectures_for_spring_2017/

**Comment by mugli** [comment]
Anyone knows any update on the videos?

**Comment by ramanpreet9** [comment]
yeah i would like to know about the video lectures too.

**Comment by leogout** [comment]
Hi,

Here is what I found:
http://cs231n.stanford.edu/syllabus.html

Hope that helps !

**Comment by moizsajid** [comment]
Attaching the link just in case anyone needs it: https://www.youtube.com/playlist?list=PLC1qU-LWwrF64f4QKQT-Vg5Wr4qEE1Zxk
