### ISSUE TITLE
problem with importing numpy

### ISSUE THREAD

**Issue by vahidajalluian** [cs231n/cs231n.github.io#170]
hello
Thanks for the course and the materials. Although I think I had prepared the prerequisites completely, when i start to work offline with jupiter notebook I have problem with importing numpy. I want to know how can i fix the problem.

![screenshot from 2017-08-23 14-16-17](https://user-images.githubusercontent.com/16366211/29609854-adaeec10-880d-11e7-82a6-8fcb755ba5c5.png)
![screenshot from 2017-08-23 14-18-32](https://user-images.githubusercontent.com/16366211/29609950-f9d99ac2-880d-11e7-82d6-a0219c25bf1e.png)
![screenshot from 2017-08-23 14-19-25](https://user-images.githubusercontent.com/16366211/29610010-29b2f6f8-880e-11e7-819c-9c35eeaad628.png)

**Comment by omoindrot** [comment]
It might have to do with jupyter not using your virtual environment.
You can ask your question on stackoverflow otherwise.
