### ISSUE TITLE
Assignment 3 GANs-PyTorch.ipynb

### ISSUE THREAD

**Issue by Burton2000** [cs231n/cs231n.github.io#171]
Only a small issue I think but in the test_lsgan_loss function of GANs-PyTorch.ipynb it is missing the cast for the inputs to torch.Tensor and wrapping them as Variables and also casting back the result to a numpy array. This would then match the test for vanilla GAN just above. 

Currently:

```python
def test_lsgan_loss(score_real, score_fake, d_loss_true, g_loss_true):
    d_loss = ls_discriminator_loss(score_real, score_fake)
    g_loss = ls_generator_loss(score_fake)
    print("Maximum error in d_loss: %g"%rel_error(d_loss_true, d_loss))
    print("Maximum error in g_loss: %g"%rel_error(g_loss_true, g_loss))
```

Should be:
```python
def test_lsgan_loss(score_real, score_fake, d_loss_true, g_loss_true):
    d_loss = ls_discriminator_loss(Variable(torch.Tensor(score_real)).type(dtype), Variable(torch.Tensor(score_fake)).type(dtype)).data.cpu().numpy()
    g_loss = ls_generator_loss(Variable(torch.Tensor(score_fake)).type(dtype)).data.cpu().numpy()
    print("Maximum error in d_loss: %g"%rel_error(d_loss_true, d_loss))
    print("Maximum error in g_loss: %g"%rel_error(g_loss_true, g_loss))
```

**Comment by JasonQSY** [comment]
+1, the current code cannot run.

**Comment by Gamrix** [comment]
This will be updated the next time we release assignment 3. `pytorch` is a constantly evolving library, for example, in version `0.4` there is no longer a distinction between a variable and a Tensor, so your fixed code is already out of date.
