### ISSUE TITLE
Assignment 2: misleading guidance in batchnorm_forward method in layers.py

### ISSUE THREAD

**Issue by vdyashin** [cs231n/cs231n.github.io#180]
In the method documentation it is stated:

```
running_mean = momentum * running_mean + (1 - momentum) * sample_mean
running_var = momentum * running_var + (1 - momentum) * sample_var
```

But it should:
```
running_mean = momentum * sample_mean + (1 - momentum) * running_mean
running_var = momentum * sample_var + (1 - momentum) * running_var
```
(Spring, 2017)

**Comment by rkaplan** [comment]
The method documentation is correct, momentum is supposed to be applied to the running estimates of the mean and variance. Momentum in general is supposed to weight the things you've already seen -- the running mean and variance parameters are weighted averages of what the network has already seen.

**Comment by vdyashin** [comment]
Thanks for the clarification. Though it does not seem that it passes the tests in the assignment for some reason.

**Comment by vdyashin** [comment]
Yeah, my bad. It seems that I have been misled by the correct checks earlier. It should be closed.

**Comment by HumbleHumbert** [comment]
what if the running_mean and sample_mean are of different dimensions, I mean, the smple mean compute the current input yet the running mean is iherited from former layer, and they don't necessarily have the same feature dimension right?
