### ISSUE TITLE
from cs231n.data_utils import load_CIFAR10   produces error    "ImportError: cannot import name 'imread'"

### ISSUE THREAD

**Issue by cpoptic** [cs231n/cs231n.github.io#190]
Using Python 3.6 (assuming an institution as reputable as Stanford would be using the most modern version of Python, Python 3).

Assignment 1.  First cell.  I have created a virtual environment and activated it.

`from cs231n.data_utils import load_CIFAR10`

```
ImportError                               Traceback (most recent call last)
<ipython-input-4-5a76ca40a88e> in <module>()
      3 import random
      4 import numpy as np
----> 5 from cs231n.data_utils import load_CIFAR10
      6 import matplotlib.pyplot as plt
      7 

D:\projects\cs231n.github.io\assignments\2018\assignment1\cs231n\data_utils.py in <module>()
      4 import numpy as np
      5 import os
----> 6 from scipy.misc import imread
      7 import platform
      8 

ImportError: cannot import name 'imread'
```

Opening the data_utils.py file from  D:\projects\cs231n.github.io\assignments\2018\assignment1\cs231n

Line 6 is `from scipy.misc import imread`

No clue what the imread package is, but it appears to be at the root problem of this.

Any idea how to solve this issue?

**Comment by cpoptic** [comment]
`(cs231n) D:\projects\cs231n.github.io>pip install pillow`

> Requirement already satisfied: pillow in c:\programdata\anaconda3\envs\cs231n\lib\site-packages (5.1.0)
> mkl-random 1.0.1 requires cython, which is not installed.
> mkl-fft 1.0.0 requires cython, which is not installed.

**Comment by Gamrix** [comment]
What version of `scipy` do you have installed?

**Comment by cpoptic** [comment]
`>>> import scipy
>>> scipy.__version__
'1.0.1'`

**Comment by cpoptic** [comment]
Figured it out, but what a pain.  Had to `pip install future`, `pip install pillow`

Then to get the virtual environment kernel to display in Jupyter lab, had to conda install `nb_conda_kernels`   or    conda install --channel=conda-forge nb_conda_kernels
https://github.com/jupyter/jupyter/issues/245

That last command got the cs231n environment kernel to display in the upper right corner of Jupyter lab.  So many hours wasted just trying to get the environment configured properly, which is frustrating because that time would've been better spent doing the actual coding assignments.  Hopefully future iterations will address this issue.

**Comment by makokiko** [comment]
Hi. I have trouble with the same error. Im not sure I even have conda on my Ubuntu. Can you help me with that? it is a pain

**Comment by BrunoGomesCoelho** [comment]
Not sure if the same problem, but my problem was with Pillow and Scipy versions - I commented about it on issue #169  [here](https://github.com/cs231n/cs231n.github.io/issues/169).

**Comment by mnslarcher** [comment]
In my case it was because scipy has deprecated imread.

https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imread.html#scipy.misc.imread

imread is deprecated! imread is deprecated in SciPy 1.0.0, and will be removed in 1.2.0. Use imageio.imread instead.

I just did this in data_utils.py to solve the issue:
# from scipy.misc import imread
from imageio import imread
