### ISSUE TITLE
Where can i get the configured IMAGE file for Google Compute Engine?

### ISSUE THREAD

**Issue by vinaykumar2491** [cs231n/cs231n.github.io#191]
Hi,

Can someone please share the IMAGE file(cs231n-repo/deep-ubuntu.tar.gz) as mentioned in the GCE tutorial.

Thanks

**Comment by domarps** [comment]
You can find details about the pre-configured disk here : https://github.com/cs231n/cs231n.github.io/blob/master/google_cloud_tutorial.md#create-an-image-from-our-provided-disk

**Comment by vinaykumar2491** [comment]
Thanks
