### ISSUE TITLE
how to draw a knn pic in assignment 1

### ISSUE THREAD

**Issue by songtaoshi** [cs231n/cs231n.github.io#217]
![image](https://user-images.githubusercontent.com/20240391/59149989-4e2afb80-8a4f-11e9-8e9a-e3a697cbb258.png)

**Comment by jcjohnson** [comment]
I can't recall exactly where this image came from, but the KNN web demo I wrote a few years back makes similar visualizations in javascript:

http://vision.stanford.edu/teaching/cs231n-demos/knn/

**Comment by songtaoshi** [comment]
Thanks a lot !!!
