### ISSUE TITLE
the image is cat

### ISSUE THREAD

**Issue by YuehChuan** [cs231n/cs231n.github.io#233]
The description say it dog.
https://cs231n.github.io/linear-classify/
![cs231_error](https://user-images.githubusercontent.com/7314531/87002201-acdf1d80-c1eb-11ea-8552-5d45bebe017b.png)

**Comment by or-toledano** [comment]
> Note that this particular set of weights W is not good at all: the weights assign our cat image a very low cat score. In particular, this set of weights seems convinced that it's looking at a dog.
It is intended to be a counterexample.

**Comment by YuehChuan** [comment]
OH Thank you! Just see picture.
