### ISSUE TITLE
cs231n.github.io couldn't open again!!

### ISSUE THREAD

**Issue by ZHJD** [cs231n/cs231n.github.io#241]
yesterday, I visit the website but get error, this morning is fine, but now the visit issue happen again! I‘m sure I can visit other website So please check it！
![image](https://user-images.githubusercontent.com/24853152/90306380-49898f00-deff-11ea-8ba9-fa1a82e74200.png)

**Comment by leobxpan** [comment]
That's unlikely an issue on our side. Please check your network configs.
