### ISSUE TITLE
Gradient calculation incorrect?  perhaps?

### ISSUE THREAD

**Issue by ArEnSc** [cs231n/cs231n.github.io#41]
http://cs231n.github.io/optimization-2/

```python
# set some inputs
x = -2; y = 5; z = -4

# perform the forward pass
q = x + y # q becomes 3
f = q * z # f becomes -12

# perform the backward pass (backpropagation) in reverse order:
# first backprop through f = q * z
dfdz = q # df/dz = q, so gradient on z becomes 3
dfdq = z # df/dq = z, so gradient on q becomes -4
# now backprop through q = x + y
dfdx = 1.0 * dfdq # dq/dx = 1. And the multiplication here is the chain rule!
dfdy = 1.0 * dfdq # dq/dy = 1

```

dfdx = 1.0 * dfdq # dq/dx = 1. And the multiplication here is the chain rule!
dfdy = 1.0 * dfdq 

Shouldn't the above be -4 ? 

In the circuit diagram it's not immediately clear where the final 1 comes from?

Also isn't the partial derivative of f(x,y,z) with respect to x = z?  also that of y.
Just to make sure I am not crazy I punched into wolfram.
http://www.wolframalpha.com/widgets/view.jsp?id=d052b64db910c143ed1f1a05298ba14c 

so I get

fx = z
fy = z
fz = x + y

meaning the gradient is

fxyz = [z,z,x+y]

so for the inputs
gradient is fxyz = [-4,-4,3] ?

I am sorry I am not sure if the mistake is on my end.

Thanks and let me know ? =)

If you can explain to me where the 1 comes from as well that would be great =)
would it be the length of the final vector?

**Comment by ArEnSc** [comment]
https://www.wolframalpha.com/input/?i=gradient+of+%28x%2By%29z+

**Comment by ArEnSc** [comment]
Alright so I have a better understanding, what you are trying to communicate you are trying to say that we in order to understand back prorogation we need to see it happen at each pass. I am still not sure where the 1 comes from though.

**Comment by ArEnSc** [comment]
Lets get an intuition for how this works by referring again to the example. The add gate received inputs [-2, 5] and computed output 3. Since the gate is computing the addition operation, its local gradient for both of its inputs is +1

isn't the local gradient for both outputs -4? as said in the diagram ?

**Comment by karpathy** [comment]
I'm not sure about the source of the confusion.

df/dy = dq/dy * df/dq

is the chain rule. In this case, since q = x + y, dq/dy = 1 (that's where the 1 is from). And df/dq = z. So the final derivatives for f w.r.t. x,y,z are exactly as you say and exactly what Wolfram Alpha gives, they are just computed in two steps each (via the chain rule).

Hope that makes sense.

**Comment by ArEnSc** [comment]
It does thanks I just had to skip parts of it, then go back, then combine it with the slides and it makes sense!
