### ISSUE TITLE
Error: "Double requirement given" when using requirements.txt for assignment1

### ISSUE THREAD

**Issue by shagunsodhani** [cs231n/cs231n.github.io#64]
Following requirements are mentioned twice in reuirements.txt that comes with the zip file for [assignemnt 1](http://cs231n.github.io/assignments2016/assignment1/).
- jupyter (1.0.0 both times)
- pillow (3.1.0 and 3.0.0)

This gives the error "Double requirement given" when running `pip install -r requirements.txt`

**Comment by nealmcb** [comment]
I see the same problem.  Removing the `Pillow==3.0.0` line and one `jupyter==1.0.0` line worked.

If someone knows a way to get pip to do a "dry run" (find out what it would do, without actually e.g. downgrading matplotlib from 1.5.1 to 1.5.0), let me know....
