### ISSUE TITLE
typo in Python tutorial

### ISSUE THREAD

**Issue by omtcyf0** [cs231n/cs231n.github.io#85]
[Python Numpy Tutorial](https://cs231n.github.io/python-numpy-tutorial/#numpy) has the following typo in [Array indexing](https://cs231n.github.io/python-numpy-tutorial/#numpy-array-indexing) section:

```
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
```

I'm pretty sure it should be
```
# Create the following rank **3** array with shape (3, 4)
```

**Comment by jcjohnson** [comment]
It's not a typo, but I agree that it is a bit ambiguous: for tensors rank usually refers to the number of dimensions, so the array is a rank 2 tensor; however the matrix rank is indeed 3.

**Comment by omtcyf0** [comment]
@jcjohnson 

Thank you a lot for the answer!

Ah, now I see. Though I wasn't able to get from the context that you are referring to the tensor rank and not to the matrix rank.
